### ISSUE TITLE
Add ners570f22 Students to Repo

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f22-SpMV#1]
The purpose of this issue is to add all the students in ners570f22 to this repo for collaboration on upcoming activities.

To complete this issues the following students should be added

- [x] Doruk
- [x] Sahil
- [x] Erin
- [x] Thomas
- [x] Connor
- [x] Soumik
- [x] Codie
- [x] Colton
- [x] Alasdair
- [x] Mohamed
- [x] Theo
- [x] Jasmin
- [x] Meichen
- [x] Yujie
- [x] Dylan
- [x] Carleen
- [x] Mahlet
- [x] Patrick
- [x] Jeongbin
- [x] Shibo
- [x] Rachel
- [x] Amanda

**Comment by myerspat** [comment]
myerspat

**Comment by erinburrell** [comment]
erinburrell

**Comment by coltongraham99** [comment]
coltongraham99

**Comment by umichyujl** [comment]
umichyujl

**Comment by tcoonsUM** [comment]
tcoonsUM

**Comment by tleasca** [comment]
tleasca

**Comment by A-CGray** [comment]
A-CGray

**Comment by sahilbhola14** [comment]
sahil

**Comment by SoumiKDaS1701** [comment]
SoumiKDaS1701

**Comment by meichenl95** [comment]
Meichen

**Comment by Connor1476** [comment]
Connor1476

**Comment by ArshSaja** [comment]
Arshsaja

**Comment by bkochuna** [comment]
@KyleVaughn This is ready for review!

**Comment by KyleVaughn** [comment]
Everyone is checked off and the number of replies to this issue and [issue 2](https://github.com/bkochuna/ners570f22-SpMV/issues/2) sum to 25, so i'm assuming the number of unique participants is around 22 students + me and @bkochuna. Closing.
