### ISSUE TITLE
Document UML Class Diagrams from Lab

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f22-SpMV#3]
## Background
As a part of learning how to do software design, we have this issue to practice as a group of coming up with a class diagram for sparse matrix formats.

## Tasks
Discuss in small groups and sketch what the classes look like for COO, CSR, ELL, DEN, JDS storage types should look like and potentially how they are associated in a class hierarchy

## Definition of Done
The whiteboard diagram have been uploaded to the issue

**Comment by bkochuna** [comment]
![image_50370817](https://user-images.githubusercontent.com/5183217/194644359-eb9998c2-8cee-4ec6-b076-755d0e73674b.JPG)

**Comment by bkochuna** [comment]
![image_50370561](https://user-images.githubusercontent.com/5183217/194644395-d3188a46-590f-4162-b37e-c8c0bd2fc2be.JPG)

**Comment by bkochuna** [comment]
![image_50340609](https://user-images.githubusercontent.com/5183217/194644420-f76dbba3-716b-490d-8a19-20714e067b1c.JPG)

**Comment by bkochuna** [comment]
![image_50338817](https://user-images.githubusercontent.com/5183217/194644446-f0f821ab-3787-4378-9fd4-808872ce2f4c.JPG)

**Comment by bkochuna** [comment]
@KyleVaughn Ready for review!

**Comment by KyleVaughn** [comment]
Four groups, four driagrams! Closing.
