### ISSUE TITLE
Create Unit Testing Template

### ISSUE THREAD

**Issue by myerspat** [bkochuna/ners570f22-SpMV#46]
## Background
A unit testing structure needs to be implemented so new methods/classes can easily be tested for bugs. This unit testing structure should be automated to reduce the users' work and should integrate with CMake. 

## Tasks
- [x] Write a CMake function that takes a test source file and defines it as an executable target in the build system, and declares that executable target as a test (2 for single and double precision)
- [x] Create an example test to show the use of assertions and test cases

## Definition of Done
The user should be able to add more unit tests for their specific functions easily with the addition of a testing file. The tests should be able to be run with Ctest.

**Comment by bkochuna** [comment]
I pushed up the unit test header to the main branch. It is in the tests folder.

**Comment by bkochuna** [comment]
Also, I think its more accurate to say "Write a CMake function that takes a test source file and defines it as an executable target in the build system, and declares that executable target as a test"

You also want it to create two executables and two tests. One for single precision, and one for double precision.
